version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - local_network
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
  city-service:
    image: city-service
    container_name: city_service
    environment:
      - ZIPCODE_SERVICE_URL=http://localhost:8080
      - JAEGER_HOST=jaeger
    depends_on:
      - "jaeger"
    links:
      - jaeger:jaeger
    networks:
      - local_network
    ports:
      - 8080:8080
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - JOBS=city-service:8080
    depends_on:
      - "city-service"
    links:
      - city-service:city-service
    networks:
      - local_network
    ports:
      - 9090:9090
    restart: unless-stopped

networks:
  local_network: