version: "2"
services:
  sonarr:
    image: city_service
    container_name: city_service
    environment:
      - ZIPCODE_SERVICE_URL="http://localhost:8080"
    ports:
      - 8080:8080
    restart: unless-stopped