openapi: 3.0.2

info:
  title: REST API Template
  description: >-
    This template illustrates the REST API Standards & Guidelines using an example.
    The focus is on the structure and 'layout' of a REST API. Therefore, the resource representations
    (in terms of data elements included) are reduced to the absolute minimum needed to illustrate
    the standards, guidelines and best practices.
  version: 1.0.0

servers:
- url: 'https://{host}:{port}/v1'
  variables:
    host:
      default: 'localhost'
    port:
      default: '443'

tags:
- name: City

paths:
  /countries/{countryCode}/cities:
    get:
      operationId: findCitiesByCountryCode
      tags:
      - City
      description: Get a list of cities matching the criteria specified
      parameters:
      - $ref: '#/components/parameters/h_traceId'
      - $ref: '#/components/parameters/h_spanId'
      - $ref: '#/components/parameters/p_countryCode'
      - $ref: '#/components/parameters/q_offset'
      - $ref: '#/components/parameters/q_limit'
      responses:
        200:
          $ref: '#/components/responses/OkWithCityList'
        201:
          $ref: '#/components/responses/Created'
        202:
          $ref: '#/components/responses/Accepted'
        204:
          $ref: '#/components/responses/NoContent'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          $ref: '#/components/responses/Conflict'
        418:
          $ref: '#/components/responses/Teapot'
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  parameters:
    h_traceId:
      name: X-B3-TraceId
      description: Used for distributed tracing. See also https://github.com/openzipkin/b3-propagation.
      in: header
      schema:
        $ref: '#/components/schemas/B3TraceId'
    h_spanId:
      name: X-B3-SpanId
      description: Used for distributed tracing. See also https://github.com/openzipkin/b3-propagation.
      in: header
      schema:
        $ref: '#/components/schemas/B3SpanId'
    p_countryCode:
      name: countryCode
      description: ISO 3166 alpha-2 country code
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/CountryCode'
    q_offset:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    q_limit:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return.

  headers:
    X-B3-TraceId:
      description: Used for distributed tracing. See also https://github.com/openzipkin/b3-propagation.
      schema:
        $ref: '#/components/schemas/B3TraceId'
    X-B3-SpanId:
      description: Used for distributed tracing. See also https://github.com/openzipkin/b3-propagation.
      schema:
        $ref: '#/components/schemas/B3SpanId'

  responses:
    OkWithCityList:
      description: Ok - List of cities returned
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CityList'
    OkWithCountry:
      description: Ok - List of cities returned
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Country'
    Created:
      description: The resource was created
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
        location:
          description: URI of the resource that was created
          required: true
          schema:
            type: string
    Accepted:
      description: >-
        The request has been accepted for processing, but the processing has not been completed. The request might
        or might not eventually be acted upon, as it might be disallowed when processing actually takes place.
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
    NoContent:
      description: Request successfully executed, no content to return
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
    BadRequest:
      description: BadRequest - An invalid request was received
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorList'
    Unauthorized:
      description: Unauthorized - The request requires valid authentication credentials, but none were provided
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
    Forbidden:
      description: Forbidden - The caller is not authorized to access this resource
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
    NotFound:
      description: Not found - The requested resource does not exist
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
    Conflict:
      description: >-
        Conflict - The resource is not in the correct state (e.g. was concurrently modified
        by another request)
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorList'
    InternalServerError:
      description: "Returns an internal server error"
      headers:
        X-B3-TraceId:
          $ref: '#/components/headers/X-B3-TraceId'
        X-B3-SpanId:
          $ref: '#/components/headers/X-B3-SpanId'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorList"

  schemas:
    B3TraceId:
      description: >-
        A distributed tracing TraceId. See also https://github.com/openzipkin/b3-propagation
      type: string
      pattern: '^[a-f0-9]{16}|[a-f0-9]{32}$'
    B3SpanId:
      description: >-
        A distributed tracing SpanId. See also https://github.com/openzipkin/b3-propagation.
      type: string
      pattern: '^[a-f0-9]{16}$'
    CountryCode:
      description: ISO 3166 alpha-2 country code
      type: string
      pattern: '[A-Z]{2}'
    CityName:
      description: Name of the city
      type: string
      maxLength: 255
    ZipCode:
      description: Zip code of a city
      type: string
      maxLength: 255
    CityList:
      type: object
      description: A list of cities.
      properties:
        count:
          description: The number of items returned.
          type: integer
          minimum: 0
        totalCount:
          description: The total number of items matching the filter criteria.
          type: integer
          minimum: 0
        items:
          type: array
          items:
            $ref: '#/components/schemas/City'
      required:
      - count
      - totalCount
      - items
    City:
      type: object
      description: Represents a typical city in any country
      properties:
        cityName:
          $ref: '#/components/schemas/CityName'
        zipCode:
          $ref: '#/components/schemas/ZipCode'
      required:
      - cityName
      - zipCode
    Country:
      type: object
      description: Represents country
      properties:
        countryCode:
          type: string
        countryName:
          type: string
        cities:
          type: array
          items:
            $ref: '#/components/schemas/City'
    ErrorList:
      type: object
      description: A list of errors.
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      required:
      - errors
    Error:
      type: object
      description: An error.
      properties:
        errorType:
          type: string
          enum:
            - 'BUSINESS'
            - 'TECHNICAL'
        errorReference:
          description: >-
            16 lower-hex characters. Used for distributed tracing. See also
            https://github.com/openzipkin/b3-propagation.
          type: string
          minLength: 16
          maxLength: 16
          pattern: '[a-f0-9]{16}'
        errorDescription:
          description: Human readable description of the error.
          type: string
        fieldName:
          description: >-
            If the error is linked to an individual field, a reference to that
            field.
          type: string
        originalValue:
          description: >-
            If the error is linked to an individual field, the original
            (erroneous) field value.
          type: string
      required:
        - errorType
        - errorReference
        - errorCode
        - errorDescription